--- 
- name: Run app on yacloud
  hosts: all
  remote_user: ubuntu
  become: true
  
  roles:
    - web_app

    # - role: web_app
    #   web_app_dir: /dart_app
    #   web_app:
    #     image: amina109/devops
    #     tag: latest
    #     external_port: 8000
    #     internal_port: 8000
    #   web_app_name: web_app
    #   web_app_full_wipe: true